name: Deployment
run-name:  EC2 Deployment 🚀
on: 
  push:
    branches:
      - main

jobs:

  EC2-Deploy:
    env:
      PRIVATE_KEY: ${{ secrets.EC2_KEY  }}
      HOSTNAME : ${{ secrets.HOSTNAME  }}
      USER_NAME : ${{ secrets.EC2_USER  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            touch website/.env &&
            ./build.sh
          '